source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JLAccordion_Example', :exclusive => true do
  pod 'JLAccordion', :path => '../'
end

target 'JLAccordion_Tests', :exclusive => true do
  pod 'JLAccordion', :path => '../'

  
end
